### ISSUE TITLE
/bin/sqlformat does not exist

### ISSUE THREAD

**Issue by ch3njust1n** [sriniiyer/codenn#1]
~/codenn/src/sqlparse$ sudo python setup.py install
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.1.16-dev' to '0.1.16.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing sqlparse.egg-info/PKG-INFO
writing top-level names to sqlparse.egg-info/top_level.txt
writing dependency_links to sqlparse.egg-info/dependency_links.txt
reading manifest file 'sqlparse.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sqlparse.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
error: file '/home/jc/codenn/src/sqlparse/bin/sqlformat' does not exist

I'm getting this error when I try to install the modified sqlparse.

**Comment by sriniiyer** [comment]
Added the file. Was not pushed because of gitignore. Should work now.
