### ISSUE TITLE
Script to calculate METEOR score

### ISSUE THREAD

**Issue by betterenvi** [sriniiyer/codenn#11]
Thank you for great job!

I am working on this dataset for a course project and benefits much from this repo.

In this repo, I only found a script that calculates **BLEU** score, could you please provide the script that calculates **METEOR** score?

Thank you very much!

**Comment by sriniiyer** [comment]
use meteorFromMaps() from here: https://paste.ubuntu.com/26405875/
It needs a map of id -> sentences, for gold and prediction.
