### ISSUE TITLE
No module named sql.SqlTemplate

### ISSUE THREAD

**Issue by zjrn** [sriniiyer/codenn#13]
Traceback (most recent call last):
  File "buildData.py", line 1, in <module>
    from sql.SqlTemplate import SqlTemplate
ImportError: No module named sql.SqlTemplate
Traceback (most recent call last):
  File "buildData.py", line 1, in <module>
    from sql.SqlTemplate import SqlTemplate
ImportError: No module named sql.SqlTemplate

I'm getting this error when i build dataset.

**Comment by sriniiyer** [comment]
Did you properly set the PYTHONPATH like this? 

`export PYTHONPATH=~/codenn/src/:~/codenn/src/sqlparse`

**Comment by Moshiii** [comment]
I am having the same problem after the export
![image](https://user-images.githubusercontent.com/7553188/86420081-677a9780-bca3-11ea-9fa9-6769ffc5bddd.png)
