### ISSUE TITLE
how to build the AST for CSharp using ANTLR?

### ISSUE THREAD

**Issue by wanyao1992** [sriniiyer/codenn#7]
In your paper, you mentioned that you have conduct experiments on the tree structure of source code, could you tell me how to build the tree for C# using ANTLR? And it will be highly appreciated if you can share the code of handling abstract syntax trees.

**Comment by sriniiyer** [comment]
The code is pretty standard and is available all over the internet. I'm traveling this week but will send it to you later if you still haven't found it. Pm me later for that.
